"""
ORM model for the patient profile table.

Mirrors the original notebook's ``PatientProfile`` with identical column semantics.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlmodel import Field, SQLModel


class PatientProfile(SQLModel, table=True):
    """Standardised patient record generated by the LLM."""

    __tablename__ = "patient_profile"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    age: str
    gender: str
    chief_complaint: str
    full_profile_json: str  # raw JSON blob – keeps all LLM-generated fields
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
